### ISSUE TITLE
Website Updates Tracker (future v2)

### ISSUE THREAD

**Issue by stachu540** [twitch4j/twitch4j.github.io#5]
### Description

This website needs to be improvment with better lookup. This update uses [VuePress v2](https://v2.vuepress.vuejs.org/). Any ideas to improvement are welcome. For example, I will give you to preview [this website](https://www.gethalfmoon.com/) - it use [Docusaurus](https://docusaurus.io/).

### General
* [ ] **USE**  [VuePress](https://v2.vuepress.vuejs.org/) - replaces HUGO
* [x] ~~Navigation enhancement~~ - No needed if we gonna migrate to  [VuePress](https://v2.vuepress.vuejs.org/)
  * [x] ~~Shrink Main Menu with buttons~~
  * [x] ~~Documentation Menu improvements (sidebar only)~~
  * [x] ~~Table of Contest improvement (needs extends required classes with SASS)~~
* [ ] Documentation improvements / updates
  * [ ] Migrate some parts to Javadoc
  * [ ] ~~Improve elements resolve with the custom [VuePress Plugin](https://v2.vuepress.vuejs.org/guide/plugin.html) to creates index~~ - #2 (Kraken is pending for removal)
  * [ ] Improve codeblocks examples to JVM specific languages (groovy, kotlin, scala)
* [ ] Enhance search index with reduced units - #4 

### Content
* [ ] v2 Migrations
* [ ] Obfuscate any kraken documentation
* [ ] v1 Archives

**Comment by iProdigy** [comment]
I believe this was resolved by #22
